name: "Release Apeleutherosis"
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - name: Build
      working-directory: ./apeleutherosis/
      run: nix-build
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: gh release create "${{ github.ref_name }}" --generate-notes ./apeleutherosis/result/share/fonts/truetype/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
