name: "Release"
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - name: Build
      run: nix-build --argstr version ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        font_files=""
        for link in $(find . -type l -name 'result*'); do
          font_files="$font_files$(find "$link/share/fonts/truetype" -type f) "
        done
        gh release create "${{ github.ref_name }}" --generate-notes $font_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
